[gcp_service_account]
type = "service_account"
project_id = "barang-dan-jasa"
private_key_id = "9bcba3a2412334d446833b61d301ed50d870a835"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZlAePfXO8rGs6
K+F/xqMX3dM0LaiGD5+PjUNPZ0j/HULH79d4fRSFP12s5equOHXVvY1WbKh0bxZ2
OMApmgYY7ZUzRE3D+jaMrZIYXHmQbviUiITZVCYymlJGsDO40pNanx9ukRdlpTVc
dSBAldovcTrwres+91gb6g+herN2QU+m5CuivTnSbnrq3jmA7+8j8JK6c6Ey4/Xt
4lIvZa1SxYwZohyXLY9yjPMIBPeBrMji8Bin1iihhucNEjHSZB05/26ZZlOyXXG2
BYdgmKKMmeITqhmI0VX+anw/Kcwf1cKdqPAKDbZ/iRFsQDuMHm5i7fg2Umrak/dR
oJkDgk8vAgMBAAECggEAMVWEkjsF/UNT1KV49D9eb9HBwV6zZpFJO+dwimbO46jG
JYztphZkC6O910cqOpoHfEg+SVdxS6nNyN9VF2gTclmLlqLn6j8L2+f76Nh38oY7
UxeBuYCXHqVFLdD3ZHU8gZ1hDvcL0YqfGBrF6AlbQ+c3PE5aJel1w83OBJzyXleA
MA7PnBOzsJy+0ZHwLHqDyjNY8lX+F4pOs+8CfiwmnlDZ2n+jfXlIztETcgmGrWtH
7rcY4BsSXQVwuRLGTfQOtppbcIlFQP00wl0ZsJHcpzxrU/khGPiIZDj9sHR94K1T
HlKwIlz0hEaKnC3v6hlfUo22SoMb4QjOB3COBUOESQKBgQDKeb6iuJRMHB5b6zdd
mImIQzoElplStlZf1gUnpOKJpKdCqD5No6H5Vu9qey6YOu/ceyuE43VYcAMwyzTu
jQvD0+ICoTnfG5djqZl/Np2BoY9m7v77KZ3ke1F2NVz1TxX2lorI2dGpbiRdvHid
tlUn7FoZh7vjMKSbPr/g5Vd4RwKBgQDCLTnF8o14jVWU8QOWuutFkZeG6iwT8QLn
XLYxq7UgO7E+1DohP9cfDztTT9xs3zhCQvib7I5DDN9cBfUtU0OVd7vo2s30uPyM
F8sa09/10+Sy6q8CTiH4ltXBT2iGz+6Y90Hfst6C2P6FrSJlfa7YpX2jFS1+FgSB
WPSPEVBN2QKBgQDD+BeaGPp3u9NqdfvNXCDpQN/7puNZGd/5vASbPUyBmlrE+l/q
91CDKzBoqDcN4iVcCd6yLRDbevarmFJv/RYBAKfEkdWYanUZYgKODQdfe0Z3gyRJ
ZhtLFExhE/8X8ua4FzbWdXQm/9K04wD+7IX5MRp3kVc56k+3boF6o58IawKBgBq4
1JmMLrHnaV6s6FyG7rfNOHglo9k+srKaTKx7P9rmvBa0aCeJPJaWpwhpFiGZeomL
4+C5Zj6N9/MXEs2hBsz8BE0gR3WlO4QgBiB0Bf8zoOaKa3k6vWwTfekzf2QGG4TL
ijI50GtbZ3OIBxLGgBhqdebKlE8kwov2bPl/XXjJAoGAPciGFemx52eqncdU178y
Qynr60sHDeNDIjFdxl9Km6zb9MC/VRSNzvGMxFBjHpCN1771jL5JJwjVClns8JCQ
g9StIDn0XCuodtmIO95ACe8DM5bSNjtuIijx7DIsbMZagUlZ3euw2brSxxccSnuy
kl7ovcDd2kf642Xsxk+q6X4=
-----END PRIVATE KEY-----"""
client_email = "streamlit-barang-dan-jasa@barang-dan-jasa.iam.gserviceaccount.com"
client_id = "104754878879147734010"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-barang-dan-jasa%40barang-dan-jasa.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
