[gcp_service_account]
type = "service_account"
project_id = "barang-dan-jasa"
private_key_id = "9bcba3a2412334d446833b61d301ed50d870a835"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCZlAePfXO8rGs6
K+F/xqMX3dM0LaiGD5+PjUNPZ0j/HULH79d4fRSFP12s5equOHXVvY1WbKh0bxZ2
OMApmgYY7ZUzRE3D+jaMrZIYXHmQbviUiITZVCYymlJGsDO40pNanx9ukRdlpTVc
dSBAldovcTrwres+91gb6g+herN2QU+m5CuivTnSbnrq3jmA7+8j8JK6c6Ey4/Xt
4lIvZa1SxYwZohyXLY9yjPMIBPeBrMji8Bin1iihhucNEjHSZB05/26ZZlOyXXG2
BYdgmKKMmeITqhmI0VX+anw/Kcwf1cKdqPAKDbZ/iRFsQDuMHm5i7fg2Umrak/dR
oJkDgk8vAgMBAAECggEAMVWEkjsF/UNT1KV49D9eb9HBwV6zZpFJO+dwimbO46jG
...
kl7ovcDd2kf642Xsxk+q6X4=
-----END PRIVATE KEY-----"""
client_email = "streamlit-barang-dan-jasa@barang-dan-jasa.iam.gserviceaccount.com"
client_id = "104754878879147734010"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-barang-dan-jasa%40barang-dan-jasa.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
